name: LLVM CLANG BUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Scripts
        uses: actions/checkout@v2      

      - name: Deploy Builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_RUN_ID: ${{ secrets.GH_RUN_ID }}
          GH_BUILD_REPO: ${{ secrets.GH_BUILD_REPO }}
          GH_REL_REPO: ${{ secrets.GH_REL_REPO }}
        run: ./ci_build.sh
      
